// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TestResult } from "./TestResult";

export type CodeSubmissionResponse = { question_id: number, success: boolean, message: string, results: Array<TestResult>, };
