// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuestionSummary } from "./QuestionSummary";

export type QuestionList = { questions: Array<QuestionSummary>, };
