// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuestionName } from "./QuestionName";

export type QuestionMDResponse = { question: string, hint: string, solution: string, id: number, next: QuestionName | null, prev: QuestionName | null, };
