// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TestResult = { is_correct: boolean, case_stdout: string, error: string | null, case_signature: string, };
